module.exports = [
	{
		news_id: 1,
		thumbnail:
			"https://www.windowscentral.com/sites/wpcentral.com/files/styles/large/public/field/image/2021/10/gta-trilogy-announcement.jpg",
		headline:
			"Remastered GTA Trilogy to get November 11 release on console and PC",
		sdesc: "Grand Theft Auto: The Trilogy – The Definitive Edition is set to launch on November 11, 2021, first available digitally on all major consoles & PC. A physical release of the trilogy is set to follow on December 6.",
		tags: [
			"gta",
			"trilogy",
			"cj",
			"claude",
			"tommy",
			"pc",
			"console",
			"release",
			"remaster",
			"definitive",
		],
		source: "https://www.windowscentral.com/gta-trilogy-will-release-digitally-november-11th-all-platforms",
		date: "22-Oct-2021",
		image1: "https://assets2.rockpapershotgun.com/gta-trilogy-remasters-art.jpg/BROK/resize/1920x1920%3E/format/jpg/quality/80/gta-trilogy-remasters-art.jpg",
		image2: "https://images.clarin.com/2021/08/16/rockstar-games-quiere-relanzar-tres___YIqMMJmk3_1200x630__1.jpg",
		ldesc1: "The forthcoming Grand Theft Auto: The Trilogy – The Definitive Edition was easily one of the most rumored and sought-after releases that fans have been speculating on for years. With the new release, three games are in the package: GTA 3, Vice City, and San Andreas. They're each set to get a major graphics overhaul, and even include some quality of life changes. <br /><br /> Rockstar Games has now provided further context around the package, including more information on its planned launch. Pre-orders for all the consoles and PC versions are now open, however, with a digital-only Nov. 11 release date. If you want to get your hands on the physical copy, you're going to have to wait, now set for Dec. 6. <br /><br /> A quick grab from the product description tells us the pre-order incentives, and what to expect from the changes.",
		ldesc2: "Rockstar initially teased the trilogy without a release date but stated that the PS4, PS5, Xbox One, Xbox Series X|S, PC, and Nintendo Switch would get the trilogy this year, and the mobile ports will follow in 2022. <br /><br /> Grand Theft Auto: The Trilogy – The Definitive Edition is now available for preorder from $60 on console and PC. GTA: San Andreas will also be included in Xbox Game Pass from Nov. 11, while GTA III joins PlayStation Now one month later on Dec. 7, 2021.",
	},
	{
		news_id: 2,
		thumbnail:
			"https://cdn.mos.cms.futurecdn.net/wfqZ9XCgEf2pyfV2kkJxwK-1024-80.jpg.webp",
		headline: "God of War is coming to PC: Here's what we know",
		sdesc: "God of War will be available on Steam on January 14, 2022. That's not so far off! It's launching at $49.99.",
		tags: ["god", "war", "kratos", "pc", "sony", "playstation","thor"],
		source: "https://www.pcgamer.com/god-of-war-pc/",
		date: "21 October 2021",
		image1: "https://happymag.tv/wp-content/uploads/2021/09/Untitled-2021-09-09T171734.171-870x524.jpg",
		image2: "https://www.pcgamesn.com/wp-content/uploads/2019/04/games-like-god-of-war-pc-900x506.jpg",
		ldesc1: "<h2>God of War's PC port sounds promising</h2><p>God of War looked amazing for a PlayStation 4 game when it released, and still made for an impressive showpiece when its PS5 upgrade added 4K 60 fps support. Naturally, that'll be an option on PC, too.</p><p>Here are the specs Sony has quoted so far:</p><ul><li>Unlocked framerate</li><li>Enhanced high fidelity graphics: higher resolution shadows, improved screen space reflections, the addition of GTAO and SSDO, and much more</li><li>Nvidia DLSS and Nvidia Reflex</li><li>Built-in support for DualShock 4 and DualSense controllers</li><li>Ultrawide 21:9 support</li></ul>",
		ldesc2: "<h2>God of War PC comes with some free stuff</h2><p>Bonus content? Bonus content. Here's what you get when you buy God of War on Steam:</p><ul><li>Death’s Vow Armor Sets for Kratos and Atreus &nbsp;&nbsp;</li><li>Exile’s Guardian Shield Skin &nbsp;&nbsp;</li><li>Buckler of the Forge Shield Skin &nbsp;&nbsp;</li><li>Shining Elven Soul Shield Skin &nbsp;&nbsp;</li><li>Dökkenshieldr Shield Skin</li></ul>",
	},
	{
		news_id: 3,
		thumbnail:
			"https://venturebeat.com/wp-content/uploads/2021/06/Xbox-Game-Pass-PC-Family_Key-Art.jpg?w=930&strip=all",
		headline:
			"Xbox Game Pass India Subscription Free for 8 Months For All Members",
		sdesc: "New subscribers can get 7 months of Xbox Game Pass Ultimate for free when they sign up and pay for the first month on any of the three tiers of Xbox Game Pass (PC, Console, Ultimate). This also applies to existing members who want to renew their subscription.",
		tags: [
			"xbox",
			"game",
			"pass",
			"offer",
			"pc",
			"gamers",
			"microsoft",
			"subscription",
			"india",
		],
		source: "https://in.ign.com/xbox-game-pass/168395/news/xbox-game-pass-india-subscription-free-for-8-months-2021",
		date: "Oct. 8, 2021",
		image1: "https://sm.ign.com/t/ign_in/screenshot/default/xbox-game-pass-titles-coming-to-the-service-in-2021_yfj5.1280.jpg",
		image2: "https://cdn.mos.cms.futurecdn.net/wuQrSDPjDDaXaq9yCLhkQS-1024-80.jpg.webp",
		ldesc1: "<h3>Xbox Game Pass India Subscription Prices</h3><p>Xbox Game Pass is available in three tiers in India:</p><ul><li>Xbox Game Pass for PC: Rs. 489/month</li><li>Xbox Game Pass for Console: Rs. 489/month</li><li>Xbox Game Pass Ultimate (PC + Console + xCloud): Rs. 699/month</li></ul>",
		ldesc2: "<p>Xbox Game Pass includes a select number of games available in the service with many being added to it every month. The new offer comes at what many gamers would call a fortunate time, with Xbox's biggest first party games, Forza Horizon 5 and Halo Infinite, releasing over the course of the next couple of months in November and December respectively. The subscription service also includes access to EA Play, which includes select EA games as well as early access trials to the company's new releases like Battlefield 2042.</p><p>Xbox Game Pass for October 2021 has seen games like Marvel's Avengers and Scarlet Nexus join the service, with more titles releasing on release day like Back 4 Blood soon. While Xbox Game Pass Ultimate includes Xbox Cloud Gaming, it is yet to be introduced in India.</p>",
	},
];
